workspace(name = "com_google_ecclesia")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Abseil. Official release from Mar 4, 2020
http_archive(
    name = "com_google_absl",
    sha256 = "d3311ead20ffce78c7fde96df803b73d0de8d992d46bdf36753954bd2d459f31",
    strip_prefix = "abseil-cpp-df3ea785d8c30a9503321a3d35ee7d35808f190d",
    urls = ["https://github.com/abseil/abseil-cpp/archive/df3ea785d8c30a9503321a3d35ee7d35808f190d.zip"],
)

# emboss. No official releases yet. Picked up a commit from Oct 9, 2019
http_archive(
    name = "com_google_emboss",
    sha256 = "e4f6984b7177481f3b6b9c3457a2f7a7662b72aa79da5c421924e7b78c124172",
    strip_prefix = "emboss-26fac66f7e295145715306a26068a9c8dc334f7b",
    urls = ["https://github.com/google/emboss/archive/26fac66f7e295145715306a26068a9c8dc334f7b.zip"],
)

# Protocol buffers. Official release 3.11.4.
http_archive(
    name = "com_google_protobuf",
    sha256 = "a79d19dcdf9139fa4b81206e318e33d245c4c9da1ffed21c87288ed4380426f9",
    strip_prefix = "protobuf-3.11.4",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz"],
)

http_archive(
    name = "rules_python",
    sha256 = "e5470e92a18aa51830db99a4d9c492cc613761d5bdb7131c04bd92b9834380f6",
    strip_prefix = "rules_python-4b84ad270387a7c439ebdccfd530e2339601ef27",
    urls = ["https://github.com/bazelbuild/rules_python/archive/4b84ad270387a7c439ebdccfd530e2339601ef27.tar.gz"],
)

http_archive(
    name = "bazel_skylib",
    sha256 = "ea5dc9a1d51b861d27608ad3bd6c177bc88d54e946cb883e9163e53c607a9b4c",
    strip_prefix = "bazel-skylib-2b38b2f8bd4b8603d610cfc651fcbb299498147f",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/2b38b2f8bd4b8603d610cfc651fcbb299498147f.tar.gz"],
)

# TensorFlow depends on "io_bazel_rules_closure" so we need this here.
# Needs to be kept in sync with the same target in TensorFlow's WORKSPACE file.
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "9b99615f73aa574a2947226c6034a6f7c319e1e42905abc4dc30ddbbb16f4a31",
    strip_prefix = "rules_closure-4a79cc6e6eea5e272fe615db7c98beb8cf8e7eb5",
    urls = [
        "http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/4a79cc6e6eea5e272fe615db7c98beb8cf8e7eb5.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/4a79cc6e6eea5e272fe615db7c98beb8cf8e7eb5.tar.gz",  # 2019-09-16
    ],
)

http_archive(
    name = "com_github_libevent_libevent",
    build_file = "@//oss:libevent.BUILD",
    sha256 = "70158101eab7ed44fd9cc34e7f247b3cae91a8e4490745d9d6eb7edc184e4d96",
    strip_prefix = "libevent-release-2.1.8-stable",
    urls = [
        "https://github.com/libevent/libevent/archive/release-2.1.8-stable.zip",
    ],
)

http_archive(
    name = "com_googlesource_code_re2",
    sha256 = "d070e2ffc5476c496a6a872a6f246bfddce8e7797d6ba605a7c8d72866743bf9",
    strip_prefix = "re2-506cfa4bffd060c06ec338ce50ea3468daa6c814",
    urls = [
        "https://github.com/google/re2/archive/506cfa4bffd060c06ec338ce50ea3468daa6c814.tar.gz",
    ],
)

http_archive(
    name = "org_tensorflow",
    # NOTE: when updating this, MAKE SURE to also update the protobuf_js runtime version
    # in third_party/workspace.bzl to >= the protobuf/protoc version provided by TF.
    sha256 = "48ddba718da76df56fd4c48b4bbf4f97f254ba269ec4be67f783684c75563ef8",
    strip_prefix = "tensorflow-2.0.0-rc0",
    urls = [
        "http://mirror.tensorflow.org/github.com/tensorflow/tensorflow/archive/v2.0.0-rc0.tar.gz",  # 2019-08-23
        "https://github.com/tensorflow/tensorflow/archive/v2.0.0-rc0.tar.gz",
    ],
)

#tensoflow. Official release 2.0.0 from Oct 18, 2019
http_archive(
    name = "com_google_tensorflow_serving",
    sha256 = "70f0847bb26bac948719d75b4760443cee88f4aa4e208c2bef1d6a6baad708a0",
    strip_prefix = "serving-b5a11f1e5388c9985a6fc56a58c3421e5f78149f",
    urls = ["https://github.com/tensorflow/serving/archive/b5a11f1e5388c9985a6fc56a58c3421e5f78149f.zip"],
)

load("@com_google_tensorflow_serving//tensorflow_serving:workspace.bzl", "tf_serving_workspace")

tf_serving_workspace()

#jsoncpp. Official release 1.9.2.
http_archive(
    name = "com_jsoncpp",
    build_file = "@//oss:jsoncpp.BUILD",
    sha256 = "77a402fb577b2e0e5d0bdc1cf9c65278915cdb25171e3452c68b6da8a561f8f0",
    strip_prefix = "jsoncpp-1.9.2",
    urls = ["https://github.com/open-source-parsers/jsoncpp/archive/1.9.2.tar.gz"],
)

http_archive(
    name = "zlib",
    build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = ["https://zlib.net/zlib-1.2.11.tar.gz"],
)

http_archive(
    name = "boringssl",
    sha256 = "c474665d0d2f1880ac1b10ec4e9d861783e2b78273777bea5a9f0d9c2f0f7f05",
    strip_prefix = "boringssl-410a461df59ec34bcf2d7c4c183c7d293d331421",
    urls = [
        "https://github.com/google/boringssl/archive/410a461df59ec34bcf2d7c4c183c7d293d331421.tar.gz",
    ],
)
