licenses(["notice"])

cc_library(
    name = "arm_sysmodel",
    hdrs = ["sysmodel.h"],
    compatible_with = ["//buildenv/target:gce"],
    visibility = ["//ecclesia:magent_library_users"],
    deps = ["@com_google_absl//absl/types:optional"],
)
