# IPMI interface libraries for management agent

licenses(["notice"])

cc_library(
    name = "ipmi",
    hdrs = ["ipmi.h"],
    visibility = ["//:magent_library_users"],
    deps = ["@com_google_absl//absl/status"],
)
