licenses(["notice"])

cc_library(
    name = "status",
    testonly = True,
    hdrs = ["status.h"],
    visibility = ["//ecclesia:library_users"],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_googletest//:gtest",
    ],
)
