# Description: Simple header only utility library that provide RAII cleanup objects

licenses(["notice"])

cc_library(
    name = "cleanup",
    hdrs = ["cleanup.h"],
    compatible_with = ["//buildenv/target:gce"],
    visibility = ["//ecclesia:library_users"],
)
