licenses(["notice"])

cc_library(
    name = "fixed_range_int",
    hdrs = ["fixed_range_int.h"],
    visibility = ["//ecclesia:library_users"],
    deps = ["@com_google_absl//absl/types:optional"],
)
