# Description:
#   Libraries for accessing Eeprom

licenses(["notice"])

package(default_visibility = ["//:magent_library_users"])

cc_library(
    name = "eeprom",
    hdrs = ["eeprom.h"],
    deps = [
        "@com_google_absl//absl/types:optional",
        "@com_google_absl//absl/types:span",
    ],
)
